[project]
name = "chapter-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "uvicorn>=0.52.4",
]

[project.scripts]
chapter-1 = "chapter_1:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
